[error] java.lang.RuntimeException: java.io.FileNotFoundException: Could not locate Hadoop executable: C:\hadoop\bin\winutils.exe -see https://wiki.apache.org/hadoop/WindowsProblems
[error] 	at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:735)
[error] 	at org.apache.hadoop.util.Shell.getReadlinkCommand(Shell.java:309)
[error] 	at org.apache.hadoop.fs.FileUtil.readLink(FileUtil.java:213)
[error] 	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileLinkStatusInternal(RawLocalFileSystem.java:1113)
[error] 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:1102)
[error] 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatus(RawLocalFileSystem.java:1073)
[error] 	at org.apache.hadoop.fs.DelegateToFileSystem.getFileLinkStatus(DelegateToFileSystem.java:133)
[error] 	at org.apache.hadoop.fs.AbstractFileSystem.renameInternal(AbstractFileSystem.java:747)
[error] 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[error] 	at org.apache.hadoop.fs.ChecksumFs.renameInternal(ChecksumFs.java:489)
[error] 	at org.apache.hadoop.fs.AbstractFileSystem.rename(AbstractFileSystem.java:720)
[error] 	at org.apache.hadoop.fs.FileContext.rename(FileContext.java:1036)
[error] 	at org.apache.spark.sql.execution.streaming.FileContextBasedCheckpointFileManager.renameTempFile(CheckpointFileManager.scala:372)
[error] 	at org.apache.spark.sql.execution.streaming.CheckpointFileManager$RenameBasedFSDataOutputStream.close(CheckpointFileManager.scala:154)
[error] 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
[error] 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
[error] 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
[error] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.close(WriterBasedJsonGenerator.java:1028)
[error] 	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4724)
[error] 	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3947)
[error] 	at org.json4s.jackson.JacksonSerialization.write(Serialization.scala:36)
[error] 	at org.apache.spark.sql.execution.streaming.StreamMetadata$.write(StreamMetadata.scala:81)
[error] 	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$streamMetadata$1(StreamExecution.scala:139)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at org.apache.spark.sql.execution.streaming.StreamExecution.<init>(StreamExecution.scala:137)
[error] 	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.<init>(MicroBatchExecution.scala:49)
[error] 	at org.apache.spark.sql.streaming.StreamingQueryManager.createQuery(StreamingQueryManager.scala:295)
[error] 	at org.apache.spark.sql.streaming.StreamingQueryManager.startQuery(StreamingQueryManager.scala:346)
[error] 	at org.apache.spark.sql.streaming.DataStreamWriter.startQuery(DataStreamWriter.scala:433)
[error] 	at org.apache.spark.sql.streaming.DataStreamWriter.startInternal(DataStreamWriter.scala:410)
[error] 	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:251)
[error] 	at consumer.consumer$.main(consumer.scala:74)
[error] 	at consumer.consumer.main(consumer.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:144)
[error] 	at sbt.Run.execute$1(Run.scala:94)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
[error] 	at sbt.Run$.executeSuccess(Run.scala:187)
[error] 	at sbt.Run.runWithLoader(Run.scala:121)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2044)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1983)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.FileNotFoundException: Could not locate Hadoop executable: C:\hadoop\bin\winutils.exe -see https://wiki.apache.org/hadoop/WindowsProblems
[error] 	at org.apache.hadoop.util.Shell.getQualifiedBinInner(Shell.java:618)
[error] 	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:591)
[error] 	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:688)
[error] 	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:79)
[error] 	at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1712)
[error] 	at org.apache.hadoop.security.SecurityUtil.setConfigurationInternal(SecurityUtil.java:99)
[error] 	at org.apache.hadoop.security.SecurityUtil.<clinit>(SecurityUtil.java:88)
[error] 	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:312)
[error] 	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:300)
[error] 	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:575)
[error] 	at org.apache.spark.util.Utils$.$anonfun$getCurrentUserName$1(Utils.scala:2416)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2416)
[error] 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:329)
[error] 	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2883)
[error] 	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:1099)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:1093)
[error] 	at consumer.consumer$.main(consumer.scala:13)
[error] 	at consumer.consumer.main(consumer.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:144)
[error] 	at sbt.Run.execute$1(Run.scala:94)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
[error] 	at sbt.Run$.executeSuccess(Run.scala:187)
[error] 	at sbt.Run.runWithLoader(Run.scala:121)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2044)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1983)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / run) java.io.FileNotFoundException: Could not locate Hadoop executable: C:\hadoop\bin\winutils.exe -see https://wiki.apache.org/hadoop/WindowsProblems
